### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/img_align_celeba/182638.jpg

### ISSUE THREAD

**Issue by weico-ctrl** [VDIGPKU/CMUA-Watermark#2]
作者你好，我目前在按照您的步骤复现这个工程时，提示了以下错误，我没有找到具体的原因，错误如下
Finished deepfake models initialization!
finished init the attacked models, only attack 2 epochs
  0%|                                                                                                                                                  | 0/312 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "universal_attack.py", line 76, in <module>
    for idx, (img_a, att_a, c_org) in enumerate(tqdm(attack_dataloader)):
  File "/home/duanwei/anaconda3/envs/cuma/lib/python3.8/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/home/duanwei/anaconda3/envs/cuma/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/duanwei/anaconda3/envs/cuma/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/duanwei/anaconda3/envs/cuma/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/duanwei/anaconda3/envs/cuma/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/duanwei/project/CMUA-Watermark-main/data.py", line 70, in __getitem__
    img = self.tf(Image.open(os.path.join(self.data_path, self.images[index])))
  File "/home/duanwei/anaconda3/envs/cuma/lib/python3.8/site-packages/PIL/Image.py", line 2904, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/img_align_celeba/182638.jpg'
data文件里包含了182638.jpg这个文件，但是并没有生成img_ailgn_celeba这个文件夹，请问这可能是什么原因造成的呢？

**Comment by Huaxingweichen** [comment]
您好，这个问题是因为没有下载数据集造成的，可以下载数据集再跑代码。
请参考readme第二步
